### ISSUE TITLE
On Screen Keyboard is not opening

### ISSUE THREAD

**Issue by anas-emtee** [Tgxcorporation/skin.nebula#7]
Hi, While using skin nebula on both android box and windows in kodi jarvis 16.1, whenever i try to use on screen keyboard, kodi crashes. I tried other skins and the keyboard appears with no problem. Please is there a solution for this problem?

Thank you

**Comment by Tgxcorporation** [comment]
I've just tried on Windows with Kodi Jarvis 16.1 and everything is ok.
BTW the file responsible for the onscreen keyboard has not been touched since the 20th september 2015: https://github.com/Tgxcorporation/skin.nebula/commits/jarvis/1080i/DialogKeyboard.xml

You have to provide me the exact steps to reproduce the issue.
